version: '3.9'

services:
  eureka:
    build: C:\Users\moham\Desktop\Microservices\EurekaServer
    ports:
      - "8761:8761"
    volumes:
      - C:\Users\moham\Desktop\Microservices\EurekaServer\target:/app

  supplierservice:
    build: C:\Users\moham\Desktop\Microservices\SupplierService
    ports:
      - "8090:8090"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/

  apigateway:
    build: C:\Users\moham\Desktop\Microservices\ApiGateway
    ports:
      - "8081:8081"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/